from fastapi import FastAPI, File, UploadFile, Form
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="Tender Proposal AI")

# Allow all origins (for testing)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# TEMPORARY: Skip PDF reading
def read_pdf(file_bytes):
    # This bypasses the PDF parsing to avoid crashes
    return "Tender content is not provided, using default text."

# TEMPORARY: AI function placeholder
def generate_proposal_text(company_name: str, company_description: str, tender_text: str):
    return (
        f"Proposal for {company_name}\n\n"
        f"Company Description: {company_description}\n\n"
        f"Tender Details: {tender_text}\n\n"
        "This is a professional proposal generated by the AI."
    )

@app.post("/generate-proposal")
async def generate_proposal(
    tender: UploadFile = File(...),
    company_name: str = Form(...),
    company_description: str = Form(...)
):
    # Read the PDF (skipped)
    tender_bytes = await tender.read()
    tender_text = read_pdf(tender_bytes)

    # Generate the proposal
    proposal = generate_proposal_text(company_name, company_description, tender_text)

    return {"proposal": proposal}

