from fastapi import FastAPI, UploadFile, Form
from fastapi.responses import JSONResponse, FileResponse
import pdfplumber
import io
from fpdf import FPDF
import os
import uuid

app = FastAPI(title="Tender Proposal AI", version="0.2.0")


# Function to read PDF content
def read_pdf(file_bytes):
    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            text = ""
            for page in pdf.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + "\n"
            return text if text.strip() != "" else "Tender content is not provided, using default text."
    except Exception as e:
        return "Error reading PDF: using default text."


# Function to generate proposal text
def generate_proposal_text(company_name, company_description, tender_text):
    proposal = f"""
Proposal for {company_name}

Company Description:
{company_description}

Tender Details:
{tender_text}

This is a professional proposal generated by Tender Proposal AI.
"""
    return proposal.strip()


# Optional: Save proposal as PDF
def save_proposal_pdf(proposal_text):
    filename = f"proposal_{uuid.uuid4().hex}.pdf"
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", size=12)
    for line in proposal_text.split("\n"):
        pdf.multi_cell(0, 10, line)
    pdf.output(filename)
    return filename


@app.post("/generate-proposal")
async def generate_proposal(
    tender: UploadFile,
    company_name: str = Form(...),
    company_description: str = Form(...),
    return_pdf: bool = Form(False)
):
    tender_bytes = await tender.read()
    tender_text = read_pdf(tender_bytes)

    proposal_text = generate_proposal_text(company_name, company_description, tender_text)

    if return_pdf:
        pdf_file = save_proposal_pdf(proposal_text)
        return FileResponse(pdf_file, media_type="application/pdf", filename="proposal.pdf")

    return JSONResponse(content={"proposal": proposal_text})


# Optional: Clean up old PDFs if needed
@app.on_event("shutdown")
def cleanup_temp_files():
    for file in os.listdir("."):
        if file.startswith("proposal_") and file.endswith(".pdf"):
            try:
                os.remove(file)
            except:
                pass


